/*
 * GANSU: GPU Accelerated Numerical Simulation Utility
 *
 * Copyright (c) 2025-2026, Hiroshima University and Fujitsu Limited
 * All rights reserved.
 *
 * This software is licensed under the BSD 3-Clause License.
 * You may obtain a copy of the license in the LICENSE file
 * located in the root directory of this source tree or at:
 * https://opensource.org/licenses/BSD-3-Clause
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/**
 * @file test_validation.cu
 * @brief Validation tests comparing GANSU results against PySCF reference values.
 *
 * Reference values generated by script/validate_with_pyscf.py
 * PySCF settings: conv_tol=1e-12, cart=True for cc-pVDZ
 */

#include <gtest/gtest.h>
#include "builder.hpp"
#include "parameter_manager.hpp"
#include <iomanip>
#include <sstream>

using namespace gansu;

// ============================================================
//  PySCF reference values
// ============================================================

// RHF / STO-3G
constexpr real_t REF_H2_RHF_STO3G = -1.1175058842;
constexpr real_t REF_H2O_RHF_STO3G = -74.9659011616;
constexpr real_t REF_NH3_RHF_STO3G = -55.4554193875;
constexpr real_t REF_CH4_RHF_STO3G = -39.7268629038;
constexpr real_t REF_N2_RHF_STO3G = -107.5006541881;
constexpr real_t REF_HF_RHF_STO3G = -98.5728469737;

// RHF / cc-pVDZ (Cartesian)
constexpr real_t REF_H2O_RHF_ccpVDZ = -76.0234907752;

// UHF / STO-3G
constexpr real_t REF_O2_UHF_STO3G = -147.6364161566; // PySCF stability-optimized

// ROHF / STO-3G
constexpr real_t REF_O2_ROHF_STO3G = -147.6324148786;

// Post-HF / H2O / STO-3G
constexpr real_t REF_H2O_MP2_STO3G_corr = -0.0389637139;
constexpr real_t REF_H2O_CCSD_STO3G_corr = -0.0543962594;
constexpr real_t REF_H2O_CCSDT_STO3G_total = -75.0203643861;
constexpr real_t REF_H2O_FCI_STO3G_corr = -0.0545225877;

// RHF / cc-pVDZ (Cartesian) - additional molecules with d-functions
constexpr real_t REF_NH3_RHF_ccpVDZ = -56.1943219246;
constexpr real_t REF_CH4_RHF_ccpVDZ = -40.1985958587;

// Post-HF / H2O / cc-pVDZ (Cartesian)
constexpr real_t REF_H2O_MP2_ccpVDZ_corr = -0.2102563512;
constexpr real_t REF_H2O_CCSD_ccpVDZ_corr = -0.2192016272;
constexpr real_t REF_H2O_CCSDT_ccpVDZ_total = -76.2461303362;

// RHF / cc-pVTZ (Cartesian) - f-functions
constexpr real_t REF_H2O_RHF_ccpVTZ = -76.0531393100;

// Post-HF / H2O / cc-pVTZ (Cartesian)
constexpr real_t REF_H2O_MP2_ccpVTZ_corr = -0.2816708958;
constexpr real_t REF_H2O_CCSD_ccpVTZ_corr = -0.2870700626;
constexpr real_t REF_H2O_CCSDT_ccpVTZ_total = -76.3484466073;

// Post-HF / NH3 / cc-pVDZ (Cartesian)
constexpr real_t REF_NH3_CCSD_ccpVDZ_corr = -0.2097206001;
constexpr real_t REF_NH3_CCSDT_ccpVDZ_total = -56.4082625771;

// Post-HF / HF / cc-pVDZ (Cartesian)
constexpr real_t REF_HFmol_RHF_ccpVDZ = -100.0167900396;
constexpr real_t REF_HFmol_CCSD_ccpVDZ_corr = -0.2139496049;
constexpr real_t REF_HFmol_CCSDT_ccpVDZ_total = -100.2328803182;

// Post-HF / CH4 / cc-pVDZ (Cartesian)
constexpr real_t REF_CH4_CCSD_ccpVDZ_corr = -0.1895739578;
constexpr real_t REF_CH4_CCSDT_ccpVDZ_total = -40.3920273941;

// EOM-CCSD excitation energies (PySCF cc.eom_rccsd.EOMEESinglet, cart=True)
// H2O geometry: O(0,0,0.127), H(0,±0.758,-0.509) Angstrom
constexpr real_t REF_H2O_EOMCCSD_STO3G_state1 = 0.4305246946;
constexpr real_t REF_H2O_EOMCCSD_STO3G_state2 = 0.4982610982;
constexpr real_t REF_H2O_EOMCCSD_STO3G_state3 = 0.5892806620;
constexpr real_t REF_H2O_EOMCCSD_STO3G_state4 = 0.6685191972;
constexpr real_t REF_H2O_EOMCCSD_STO3G_state5 = 0.7853013654;
constexpr real_t REF_H2O_EOMCCSD_ccpVDZ_state1 = 0.2880084538;
constexpr real_t REF_H2O_EOMCCSD_ccpVDZ_state2 = 0.3631224086;
constexpr real_t REF_H2O_EOMCCSD_ccpVDZ_state3 = 0.3961594994;
constexpr real_t REF_H2O_EOMCCSD_ccpVDZ_state4 = 0.4725058028;
constexpr real_t REF_H2O_EOMCCSD_ccpVDZ_state5 = 0.5165295118;

// CIS (TDA) excitation energies (PySCF tdscf.TDA)
constexpr real_t REF_H2_CIS_STO3G_state1 = 0.9816694731;
constexpr real_t REF_H2O_CIS_STO3G_state1 = 0.4588134662;
constexpr real_t REF_H2O_CIS_STO3G_state2 = 0.5149577020;
constexpr real_t REF_H2O_CIS_STO3G_state3 = 0.6048024605;
constexpr real_t REF_H2O_CIS_STO3G_state4 = 0.6719940124;
constexpr real_t REF_H2O_CIS_STO3G_state5 = 0.7662676862;
constexpr real_t REF_H2O_CIS_ccpVDZ_state1 = 0.3262250094;
constexpr real_t REF_H2O_CIS_ccpVDZ_state2 = 0.3896942780;
constexpr real_t REF_H2O_CIS_ccpVDZ_state3 = 0.4309507383;
constexpr real_t REF_H2O_CIS_ccpVDZ_state4 = 0.4949266448;
constexpr real_t REF_H2O_CIS_ccpVDZ_state5 = 0.5201721546;

// CIS oscillator strengths (PySCF tdscf.TDA oscillator_strength())
constexpr real_t REF_H2_CIS_STO3G_f1 = 1.0950117176;
constexpr real_t REF_H2O_CIS_STO3G_f1 = 0.0030390894;
constexpr real_t REF_H2O_CIS_STO3G_f2 = 0.0000000000;
constexpr real_t REF_H2O_CIS_STO3G_f3 = 0.0813743886;
constexpr real_t REF_H2O_CIS_STO3G_f4 = 0.0368056217;
constexpr real_t REF_H2O_CIS_STO3G_f5 = 1.1308446622;
constexpr real_t REF_H2O_CIS_ccpVDZ_f1 = 0.0237219399;
constexpr real_t REF_H2O_CIS_ccpVDZ_f2 = 0.0000000000;
constexpr real_t REF_H2O_CIS_ccpVDZ_f3 = 0.1157568941;
constexpr real_t REF_H2O_CIS_ccpVDZ_f4 = 0.0861909444;
constexpr real_t REF_H2O_CIS_ccpVDZ_f5 = 0.3467130987;

// Tolerances
constexpr real_t TOL_POSTHF_TZ = 2e-5;  // Post-HF tolerance for cc-pVTZ (spin-orbital accumulates more FP error with 2x indices)
constexpr real_t TOL_HF = 1e-6;       // HF total energy tolerance
constexpr real_t TOL_POSTHF = 2e-6;   // Post-HF correlation energy tolerance (STO-3G)
constexpr real_t TOL_POSTHF_DZ = 5e-6; // Post-HF tolerance for cc-pVDZ (larger basis)
constexpr real_t TOL_RI = 2e-3;       // RI approximation tolerance (inherent fitting error)
constexpr real_t TOL_RI_AUTO = 5e-2;  // Auto-generated auxiliary basis tolerance (less accurate than optimized fitting basis)
constexpr real_t TOL_CIS = 2e-6;     // CIS excitation energy tolerance
constexpr real_t TOL_EOMCCSD = 3e-3;  // EOM-CCSD excitation energy tolerance (STO-3G ~2.5 mHa, cc-pVDZ ~0.6 mHa)
constexpr real_t TOL_OSC = 3e-3;     // Oscillator strength tolerance (SCF convergence differences amplified via MO coefficients)


// ============================================================
//  Helper: run GANSU calculation
// ============================================================

struct GansuResult {
    real_t hf_total_energy;
    real_t post_hf_energy;   // correlation energy (0 if no post-HF)
    std::vector<real_t> excitation_energies;  // excitation energies (CIS/EOM)
    std::vector<real_t> oscillator_strengths;  // oscillator strengths (CIS/EOM)
};

static GansuResult run_gansu(const std::string& xyz,
                              const std::string& basis,
                              const std::string& method,
                              const std::string& post_hf = "none",
                              int charge = 0,
                              int beta_to_alpha = 0,
                              const std::string& initial_guess = "core",
                              const std::string& eri_method = "stored",
                              const std::string& auxiliary_basis = "",
                              int ccsd_algorithm = 0,
                              const std::string& hash_fock_method = "compact")
{
    // Clear any sticky CUDA errors from previous tests
    cudaDeviceSynchronize();
    cudaGetLastError();

    ParameterManager params;
    params["xyzfilename"] = xyz;
    params["gbsfilename"] = basis;
    params["method"] = method;
    params["post_hf_method"] = post_hf;
    params["convergence_energy_threshold"] = "1e-10";
    params["charge"] = std::to_string(charge);
    params["beta_to_alpha"] = std::to_string(beta_to_alpha);
    params["initial_guess"] = initial_guess;
    params["eri_method"] = eri_method;
    if (!auxiliary_basis.empty()) {
        params["auxiliary_gbsfilename"] = auxiliary_basis;
    }
    if (ccsd_algorithm != 0) {
        params["ccsd_algorithm"] = std::to_string(ccsd_algorithm);
    }
    if (eri_method == "hash") {
        params["hash_fock_method"] = hash_fock_method;
    }

    // Suppress GANSU's verbose output during solve
    std::streambuf* orig_buf = std::cout.rdbuf();
    std::ostringstream null_stream;
    std::cout.rdbuf(null_stream.rdbuf());

    auto hf = HFBuilder::buildHF(params);
    hf->solve();

    // Restore stdout
    std::cout.rdbuf(orig_buf);

    GansuResult result;
    result.hf_total_energy = hf->get_total_energy();
    result.post_hf_energy = hf->get_post_hf_energy();
    result.excitation_energies = hf->get_excitation_energies();

    std::cout << std::setprecision(10) << std::fixed
              << "  GANSU HF total = " << result.hf_total_energy;
    if (post_hf != "none") {
        std::cout << "  post-HF corr = " << result.post_hf_energy
                  << "  total = " << result.hf_total_energy + result.post_hf_energy;
    }
    if (!result.excitation_energies.empty()) {
        std::cout << "  excitation[0] = " << result.excitation_energies[0];
    }
    std::cout << std::endl;

    return result;
}

// Path prefix (test runs from test/build/)
static const std::string XYZ = "../xyz/";
static const std::string BASIS = "../basis/";
static const std::string AUX_BASIS = "../auxiliary_basis/";


// ============================================================
//  RHF / STO-3G
// ============================================================

TEST(ValidationRHF, H2_STO3G) {
    auto r = run_gansu(XYZ + "H2.xyz", BASIS + "sto-3g.gbs", "rhf");
    EXPECT_NEAR(r.hf_total_energy, REF_H2_RHF_STO3G, TOL_HF);
}

TEST(ValidationRHF, H2O_STO3G) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_HF);
}

TEST(ValidationRHF, NH3_STO3G) {
    auto r = run_gansu(XYZ + "NH3.xyz", BASIS + "sto-3g.gbs", "rhf");
    EXPECT_NEAR(r.hf_total_energy, REF_NH3_RHF_STO3G, TOL_HF);
}

TEST(ValidationRHF, CH4_STO3G) {
    auto r = run_gansu(XYZ + "CH4.xyz", BASIS + "sto-3g.gbs", "rhf");
    EXPECT_NEAR(r.hf_total_energy, REF_CH4_RHF_STO3G, TOL_HF);
}

TEST(ValidationRHF, N2_STO3G) {
    auto r = run_gansu(XYZ + "N2.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "none", 0, 0, "gwh");
    EXPECT_NEAR(r.hf_total_energy, REF_N2_RHF_STO3G, TOL_HF);
}

TEST(ValidationRHF, HF_STO3G) {
    auto r = run_gansu(XYZ + "HF.xyz", BASIS + "sto-3g.gbs", "rhf");
    EXPECT_NEAR(r.hf_total_energy, REF_HF_RHF_STO3G, TOL_HF);
}


// ============================================================
//  RHF / cc-pVDZ (with d-functions)
// ============================================================

TEST(ValidationRHF, H2O_ccpVDZ) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_HF);
}


// ============================================================
//  ROHF / STO-3G
// ============================================================

TEST(ValidationROHF, O2_STO3G) {
    auto r = run_gansu(XYZ + "O2.xyz", BASIS + "sto-3g.gbs", "rohf",
                       "none", 0, 1, "core");
    EXPECT_NEAR(r.hf_total_energy, REF_O2_ROHF_STO3G, TOL_HF);
}


// ============================================================
//  UHF / STO-3G
// ============================================================

TEST(ValidationUHF, O2_STO3G) {
    auto r = run_gansu(XYZ + "O2.xyz", BASIS + "sto-3g.gbs", "uhf",
                       "none", 0, 1, "gwh");
    EXPECT_NEAR(r.hf_total_energy, REF_O2_UHF_STO3G, TOL_HF);
}


// ============================================================
//  Post-HF / H2O / STO-3G
// ============================================================

TEST(ValidationPostHF, H2O_MP2_STO3G) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf", "mp2");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_MP2_STO3G_corr, TOL_POSTHF);
}

TEST(ValidationPostHF, H2O_CCSD_STO3G) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf", "ccsd");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_CCSD_STO3G_corr, TOL_POSTHF);
}

TEST(ValidationPostHF, H2O_CCSD_T_STO3G) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf", "ccsd_t");
    real_t total = r.hf_total_energy + r.post_hf_energy;
    EXPECT_NEAR(total, REF_H2O_CCSDT_STO3G_total, TOL_POSTHF);
}

TEST(ValidationPostHF, H2O_FCI_STO3G) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf", "fci");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_FCI_STO3G_corr, TOL_POSTHF);
}


// ============================================================
//  Post-HF / H2O / cc-pVDZ (with d-functions)
// ============================================================

TEST(ValidationPostHF, H2O_MP2_ccpVDZ) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf", "mp2");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_MP2_ccpVDZ_corr, TOL_POSTHF);
}

TEST(ValidationPostHF, H2O_CCSD_ccpVDZ) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf", "ccsd");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_CCSD_ccpVDZ_corr, TOL_POSTHF_DZ);
}


TEST(ValidationPostHF, H2O_CCSD_T_ccpVDZ) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf", "ccsd_t");
    real_t total = r.hf_total_energy + r.post_hf_energy;
    std::cout << "  H2O CCSD(T)/cc-pVDZ total = " << std::fixed << std::setprecision(10)
              << total << std::endl;
    EXPECT_NEAR(total, REF_H2O_CCSDT_ccpVDZ_total, TOL_POSTHF_DZ);
}


// ============================================================
//  RHF / cc-pVDZ - additional molecules (d-functions)
// ============================================================

TEST(ValidationRHF, NH3_ccpVDZ) {
    auto r = run_gansu(XYZ + "NH3.xyz", BASIS + "cc-pvdz.gbs", "rhf");
    EXPECT_NEAR(r.hf_total_energy, REF_NH3_RHF_ccpVDZ, TOL_HF);
}

TEST(ValidationRHF, CH4_ccpVDZ) {
    auto r = run_gansu(XYZ + "CH4.xyz", BASIS + "cc-pvdz.gbs", "rhf");
    EXPECT_NEAR(r.hf_total_energy, REF_CH4_RHF_ccpVDZ, TOL_HF);
}


// ============================================================
//  RHF / cc-pVTZ (f-functions)
// ============================================================

TEST(ValidationRHF, H2O_ccpVTZ) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvtz.gbs", "rhf");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVTZ, TOL_HF);
}


// ============================================================
//  Post-HF / H2O / cc-pVTZ (f-functions)
// ============================================================

TEST(ValidationPostHF, H2O_MP2_ccpVTZ) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvtz.gbs", "rhf", "mp2");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVTZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_MP2_ccpVTZ_corr, TOL_POSTHF);
}


// ============================================================
//  Direct-SCF (should match Stored ERI exactly)
// ============================================================

TEST(ValidationDirect, H2O_RHF_STO3G) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "none", 0, 0, "core", "direct");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_HF);
}

TEST(ValidationDirect, H2O_RHF_ccpVDZ) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "none", 0, 0, "core", "direct");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_HF);
}

TEST(ValidationDirect, NH3_RHF_STO3G) {
    auto r = run_gansu(XYZ + "NH3.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "none", 0, 0, "core", "direct");
    EXPECT_NEAR(r.hf_total_energy, REF_NH3_RHF_STO3G, TOL_HF);
}


// ============================================================
//  RI approximation (looser tolerance due to fitting)
// ============================================================

TEST(ValidationRI, H2O_RHF_ccpVDZ) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "none", 0, 0, "core", "ri",
                       AUX_BASIS + "cc-pvdz-rifit.gbs");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_RI);
}

TEST(ValidationRI, NH3_RHF_ccpVDZ) {
    auto r = run_gansu(XYZ + "NH3.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "none", 0, 0, "core", "ri",
                       AUX_BASIS + "cc-pvdz-rifit.gbs");
    EXPECT_NEAR(r.hf_total_energy, REF_NH3_RHF_ccpVDZ, TOL_RI);
}

TEST(ValidationRI, CH4_RHF_ccpVDZ) {
    auto r = run_gansu(XYZ + "CH4.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "none", 0, 0, "core", "ri",
                       AUX_BASIS + "cc-pvdz-rifit.gbs");
    EXPECT_NEAR(r.hf_total_energy, REF_CH4_RHF_ccpVDZ, TOL_RI);
}

// ============================================================
//  RI approximation with auto-generated auxiliary basis
// ============================================================

TEST(ValidationRI_Auto, H2O_RHF_STO3G) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "none", 0, 0, "core", "ri");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_RI_AUTO);
}

TEST(ValidationRI_Auto, H2O_RHF_ccpVDZ) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "none", 0, 0, "core", "ri");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_RI_AUTO);
}

TEST(ValidationRI_Auto, NH3_RHF_STO3G) {
    auto r = run_gansu(XYZ + "NH3.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "none", 0, 0, "core", "ri");
    EXPECT_NEAR(r.hf_total_energy, REF_NH3_RHF_STO3G, TOL_RI_AUTO);
}

TEST(ValidationRI_Auto, CH4_RHF_STO3G) {
    auto r = run_gansu(XYZ + "CH4.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "none", 0, 0, "core", "ri");
    EXPECT_NEAR(r.hf_total_energy, REF_CH4_RHF_STO3G, TOL_RI_AUTO);
}

// ============================================================

TEST(ValidationRI, H2O_MP2_ccpVDZ) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "mp2", 0, 0, "core", "ri",
                       AUX_BASIS + "cc-pvdz-rifit.gbs");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_RI);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_MP2_ccpVDZ_corr, TOL_RI);
}

// ============================================================
//  RI post-HF: reconstruct AO ERI from B matrix, then run post-HF
//  Tolerance is TOL_RI because the RI SCF energy has fitting error,
//  but post-HF correlation with reconstructed ERI should be close.
// ============================================================

TEST(ValidationRI_PostHF, H2O_MP3_ccpVDZ) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "mp3", 0, 0, "core", "ri",
                       AUX_BASIS + "cc-pvdz-rifit.gbs");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_RI);
}

TEST(ValidationRI_PostHF, H2O_CCSD_ccpVDZ) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "ri",
                       AUX_BASIS + "cc-pvdz-rifit.gbs");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_RI);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_CCSD_ccpVDZ_corr, TOL_RI);
}

TEST(ValidationRI_PostHF, H2O_CCSD_T_ccpVDZ) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "ri",
                       AUX_BASIS + "cc-pvdz-rifit.gbs");
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy, REF_H2O_CCSDT_ccpVDZ_total, TOL_RI);
}

TEST(ValidationRI_PostHF, H2O_CIS_STO3G) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "cis", 0, 0, "core", "ri",
                       AUX_BASIS + "cc-pvdz-rifit.gbs");
    // CIS excitation energy should be close to stored ERI result
    ASSERT_FALSE(r.excitation_energies.empty());
    EXPECT_NEAR(r.excitation_energies[0], REF_H2O_EOMCCSD_STO3G_state1, 0.1);
    // CIS ≠ EOM-CCSD, so use loose tolerance — just check it runs and gives reasonable values
}

TEST(ValidationRI_PostHF, H2O_FCI_STO3G) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "fci", 0, 0, "core", "ri",
                       AUX_BASIS + "cc-pvdz-rifit.gbs");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_RI);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_FCI_STO3G_corr, TOL_RI);
}

// ADC(2) and EOM-CCSD RI tests are placed later (after reference value definitions)


// ============================================================
//  Benchmark: CCSD algorithm comparison (3 implementations)
//  Algorithm 0 = spatial-optimized (GPU DGEMM + sub-blocks)
//  Algorithm 1 = spatial-naive (no GPU, no sub-blocks)
//  Algorithm 2 = spin-orbital (legacy)
// ============================================================

// --- H2O / STO-3G / CCSD ---

TEST(BenchmarkCCSD, H2O_STO3G_SpatialOptimized) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 0);
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_CCSD_STO3G_corr, TOL_POSTHF);
}

TEST(BenchmarkCCSD, H2O_STO3G_SpatialNaive) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 1);
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_CCSD_STO3G_corr, TOL_POSTHF);
}

TEST(BenchmarkCCSD, H2O_STO3G_SpinOrbital) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 2);
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_CCSD_STO3G_corr, TOL_POSTHF);
}

// --- H2O / STO-3G / CCSD(T) ---

TEST(BenchmarkCCSD_T, H2O_STO3G_SpatialOptimized) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 0);
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy,
                REF_H2O_CCSDT_STO3G_total, TOL_POSTHF);
}

TEST(BenchmarkCCSD_T, H2O_STO3G_SpatialNaive) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 1);
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy,
                REF_H2O_CCSDT_STO3G_total, TOL_POSTHF);
}

TEST(BenchmarkCCSD_T, H2O_STO3G_SpinOrbital) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 2);
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy,
                REF_H2O_CCSDT_STO3G_total, TOL_POSTHF);
}

// --- H2O / cc-pVDZ / CCSD ---

TEST(BenchmarkCCSD, H2O_ccpVDZ_SpatialOptimized) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 0);
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_CCSD_ccpVDZ_corr, TOL_POSTHF_DZ);
}

TEST(BenchmarkCCSD, H2O_ccpVDZ_SpatialNaive) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 1);
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_CCSD_ccpVDZ_corr, TOL_POSTHF_DZ);
}

TEST(BenchmarkCCSD, H2O_ccpVDZ_SpinOrbital) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 2);
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_CCSD_ccpVDZ_corr, TOL_POSTHF_DZ);
}

// --- H2O / cc-pVDZ / CCSD(T) ---

TEST(BenchmarkCCSD_T, H2O_ccpVDZ_SpatialOptimized) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 0);
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy,
                REF_H2O_CCSDT_ccpVDZ_total, TOL_POSTHF_DZ);
}

TEST(BenchmarkCCSD_T, H2O_ccpVDZ_SpatialNaive) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 1);
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy,
                REF_H2O_CCSDT_ccpVDZ_total, TOL_POSTHF_DZ);
}

TEST(BenchmarkCCSD_T, H2O_ccpVDZ_SpinOrbital) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 2);
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy,
                REF_H2O_CCSDT_ccpVDZ_total, TOL_POSTHF_DZ);
}

// ============================================================
//  Large-scale CCSD/CCSD(T) benchmarks
//  Spatial-optimized (algo=0) vs Spin-orbital (algo=2)
//  Naive (algo=1) excluded — too slow for large basis/molecules
// ============================================================

// --- H2O / cc-pVTZ (nocc=5, nvir=60) — key scaling test ---

TEST(LargeBenchmarkCCSD, H2O_ccpVTZ_SpatialOptimized) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvtz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 0);
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVTZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_CCSD_ccpVTZ_corr, TOL_POSTHF_TZ);
}

TEST(LargeBenchmarkCCSD, H2O_ccpVTZ_SpinOrbital) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvtz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 2);
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVTZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_CCSD_ccpVTZ_corr, TOL_POSTHF_TZ);
}

TEST(LargeBenchmarkCCSD_T, H2O_ccpVTZ_SpatialOptimized) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvtz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 0);
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy,
                REF_H2O_CCSDT_ccpVTZ_total, TOL_POSTHF_TZ);
}

TEST(LargeBenchmarkCCSD_T, H2O_ccpVTZ_SpinOrbital) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvtz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 2);
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy,
                REF_H2O_CCSDT_ccpVTZ_total, TOL_POSTHF_TZ);
}

// --- NH3 / cc-pVDZ (nocc=5, nvir=25) ---

TEST(LargeBenchmarkCCSD, NH3_ccpVDZ_SpatialOptimized) {
    auto r = run_gansu(XYZ + "NH3.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 0);
    EXPECT_NEAR(r.hf_total_energy, REF_NH3_RHF_ccpVDZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_NH3_CCSD_ccpVDZ_corr, TOL_POSTHF_DZ);
}

TEST(LargeBenchmarkCCSD, NH3_ccpVDZ_SpinOrbital) {
    auto r = run_gansu(XYZ + "NH3.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 2);
    EXPECT_NEAR(r.hf_total_energy, REF_NH3_RHF_ccpVDZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_NH3_CCSD_ccpVDZ_corr, TOL_POSTHF_DZ);
}

TEST(LargeBenchmarkCCSD_T, NH3_ccpVDZ_SpatialOptimized) {
    auto r = run_gansu(XYZ + "NH3.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 0);
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy,
                REF_NH3_CCSDT_ccpVDZ_total, TOL_POSTHF_DZ);
}

TEST(LargeBenchmarkCCSD_T, NH3_ccpVDZ_SpinOrbital) {
    auto r = run_gansu(XYZ + "NH3.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 2);
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy,
                REF_NH3_CCSDT_ccpVDZ_total, TOL_POSTHF_DZ);
}

// --- CH4 / cc-pVDZ (nocc=5, nvir=30) ---

TEST(LargeBenchmarkCCSD, CH4_ccpVDZ_SpatialOptimized) {
    auto r = run_gansu(XYZ + "CH4.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 0);
    EXPECT_NEAR(r.hf_total_energy, REF_CH4_RHF_ccpVDZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_CH4_CCSD_ccpVDZ_corr, TOL_POSTHF_DZ);
}

TEST(LargeBenchmarkCCSD, CH4_ccpVDZ_SpinOrbital) {
    auto r = run_gansu(XYZ + "CH4.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 2);
    EXPECT_NEAR(r.hf_total_energy, REF_CH4_RHF_ccpVDZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_CH4_CCSD_ccpVDZ_corr, TOL_POSTHF_DZ);
}

TEST(LargeBenchmarkCCSD_T, CH4_ccpVDZ_SpatialOptimized) {
    auto r = run_gansu(XYZ + "CH4.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 0);
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy,
                REF_CH4_CCSDT_ccpVDZ_total, TOL_POSTHF_DZ);
}

TEST(LargeBenchmarkCCSD_T, CH4_ccpVDZ_SpinOrbital) {
    auto r = run_gansu(XYZ + "CH4.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 2);
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy,
                REF_CH4_CCSDT_ccpVDZ_total, TOL_POSTHF_DZ);
}

// --- HF molecule / cc-pVDZ (nocc=5, nvir=15) ---

TEST(LargeBenchmarkCCSD, HFmol_ccpVDZ_SpatialOptimized) {
    auto r = run_gansu(XYZ + "HF.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 0);
    EXPECT_NEAR(r.hf_total_energy, REF_HFmol_RHF_ccpVDZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_HFmol_CCSD_ccpVDZ_corr, TOL_POSTHF_DZ);
}

TEST(LargeBenchmarkCCSD, HFmol_ccpVDZ_SpinOrbital) {
    auto r = run_gansu(XYZ + "HF.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 2);
    EXPECT_NEAR(r.hf_total_energy, REF_HFmol_RHF_ccpVDZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_HFmol_CCSD_ccpVDZ_corr, TOL_POSTHF_DZ);
}

TEST(LargeBenchmarkCCSD_T, HFmol_ccpVDZ_SpatialOptimized) {
    auto r = run_gansu(XYZ + "HF.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 0);
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy,
                REF_HFmol_CCSDT_ccpVDZ_total, TOL_POSTHF_DZ);
}

TEST(LargeBenchmarkCCSD_T, HFmol_ccpVDZ_SpinOrbital) {
    auto r = run_gansu(XYZ + "HF.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 2);
    EXPECT_NEAR(r.hf_total_energy + r.post_hf_energy,
                REF_HFmol_CCSDT_ccpVDZ_total, TOL_POSTHF_DZ);
}

// ============================================================
//  PySCF comparison benchmarks: CCSD and CCSD(T) separately
//  Matches script/benchmark_ccsd_pyscf.py combinations
//  (H2O already covered in BenchmarkCCSD/BenchmarkCCSD_T above)
// ============================================================

// --- Formaldehyde / cc-pVDZ (nocc=8, nvir=32) --- medium molecule

TEST(BenchmarkCCSD, Formaldehyde_ccpVDZ_Spatial) {
    auto r = run_gansu(XYZ + "Formaldehyde.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 0);
}

TEST(BenchmarkCCSD, Formaldehyde_ccpVDZ_SpinOrbital) {
    auto r = run_gansu(XYZ + "Formaldehyde.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 2);
}

TEST(BenchmarkCCSD_T, Formaldehyde_ccpVDZ_Spatial) {
    auto r = run_gansu(XYZ + "Formaldehyde.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 0);
}

TEST(BenchmarkCCSD_T, Formaldehyde_ccpVDZ_SpinOrbital) {
    auto r = run_gansu(XYZ + "Formaldehyde.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 2);
}

// --- NH3 / cc-pVTZ (nocc=5, nvir=53) --- large basis scaling

TEST(BenchmarkCCSD, NH3_ccpVTZ_Spatial) {
    auto r = run_gansu(XYZ + "NH3.xyz", BASIS + "cc-pvtz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 0);
}

TEST(BenchmarkCCSD, NH3_ccpVTZ_SpinOrbital) {
    auto r = run_gansu(XYZ + "NH3.xyz", BASIS + "cc-pvtz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "stored", "", 2);
}

TEST(BenchmarkCCSD_T, NH3_ccpVTZ_Spatial) {
    auto r = run_gansu(XYZ + "NH3.xyz", BASIS + "cc-pvtz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 0);
}

TEST(BenchmarkCCSD_T, NH3_ccpVTZ_SpinOrbital) {
    auto r = run_gansu(XYZ + "NH3.xyz", BASIS + "cc-pvtz.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "stored", "", 2);
}


// ============================================================
//  CIS Excited States
// ============================================================
// Reference values can be generated with PySCF:
//   from pyscf import gto, scf, tdscf
//   mol = gto.M(atom='...', basis='sto-3g')
//   mf = scf.RHF(mol); mf.conv_tol=1e-12; mf.kernel()
//   td = tdscf.TDA(mf); td.nstates=N; td.kernel()
//   print(td.e)  # excitation energies in Hartree

static GansuResult run_gansu_cis(const std::string& xyz,
                                  const std::string& basis,
                                  int n_states = 5)
{
    // Clear any sticky CUDA errors from previous tests
    cudaDeviceSynchronize();
    cudaGetLastError();

    ParameterManager params;
    params["xyzfilename"] = xyz;
    params["gbsfilename"] = basis;
    params["method"] = "rhf";
    params["post_hf_method"] = "cis";
    params["n_excited_states"] = std::to_string(n_states);
    params["convergence_energy_threshold"] = "1e-10";
    params["initial_guess"] = "core";
    params["eri_method"] = "stored";

    // Suppress verbose output during solve
    std::streambuf* orig_buf = std::cout.rdbuf();
    std::ostringstream null_stream;
    std::cout.rdbuf(null_stream.rdbuf());

    auto hf = HFBuilder::buildHF(params);
    hf->solve();

    // Restore stdout
    std::cout.rdbuf(orig_buf);

    GansuResult result;
    result.hf_total_energy = hf->get_total_energy();
    result.post_hf_energy = hf->get_post_hf_energy();
    result.excitation_energies = hf->get_excitation_energies();
    result.oscillator_strengths = hf->get_oscillator_strengths();

    std::cout << std::setprecision(10) << std::fixed
              << "  GANSU HF total = " << result.hf_total_energy;
    for (size_t i = 0; i < result.excitation_energies.size(); i++) {
        std::cout << "  CIS[" << i << "] = " << result.excitation_energies[i];
    }
    std::cout << std::endl;

    return result;
}

TEST(ValidationCIS, H2_STO3G) {
    // H2 has 1 occ, 1 vir -> CIS dimension = 1
    auto r = run_gansu_cis(XYZ + "H2.xyz", BASIS + "sto-3g.gbs", 1);

    EXPECT_NEAR(r.hf_total_energy, REF_H2_RHF_STO3G, TOL_HF);
    ASSERT_EQ(r.excitation_energies.size(), 1u);
    EXPECT_NEAR(r.excitation_energies[0], REF_H2_CIS_STO3G_state1, TOL_CIS);
    ASSERT_EQ(r.oscillator_strengths.size(), 1u);
    EXPECT_NEAR(r.oscillator_strengths[0], REF_H2_CIS_STO3G_f1, TOL_OSC);
}

TEST(ValidationCIS, H2O_STO3G) {
    // H2O has 5 occ, 2 vir -> CIS dimension = 10
    auto r = run_gansu_cis(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", 5);

    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_HF);
    ASSERT_EQ(r.excitation_energies.size(), 5u);
    EXPECT_NEAR(r.excitation_energies[0], REF_H2O_CIS_STO3G_state1, TOL_CIS);
    EXPECT_NEAR(r.excitation_energies[1], REF_H2O_CIS_STO3G_state2, TOL_CIS);
    EXPECT_NEAR(r.excitation_energies[2], REF_H2O_CIS_STO3G_state3, TOL_CIS);
    EXPECT_NEAR(r.excitation_energies[3], REF_H2O_CIS_STO3G_state4, TOL_CIS);
    EXPECT_NEAR(r.excitation_energies[4], REF_H2O_CIS_STO3G_state5, TOL_CIS);
    ASSERT_EQ(r.oscillator_strengths.size(), 5u);
    EXPECT_NEAR(r.oscillator_strengths[0], REF_H2O_CIS_STO3G_f1, TOL_OSC);
    EXPECT_NEAR(r.oscillator_strengths[1], REF_H2O_CIS_STO3G_f2, TOL_OSC);
    EXPECT_NEAR(r.oscillator_strengths[2], REF_H2O_CIS_STO3G_f3, TOL_OSC);
    EXPECT_NEAR(r.oscillator_strengths[3], REF_H2O_CIS_STO3G_f4, TOL_OSC);
    EXPECT_NEAR(r.oscillator_strengths[4], REF_H2O_CIS_STO3G_f5, TOL_OSC);
}

TEST(ValidationCIS, H2O_ccpVDZ) {
    // H2O / cc-pVDZ: 5 occ, 20 vir -> CIS dimension = 100
    auto r = run_gansu_cis(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", 5);

    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_HF);
    ASSERT_EQ(r.excitation_energies.size(), 5u);
    EXPECT_NEAR(r.excitation_energies[0], REF_H2O_CIS_ccpVDZ_state1, TOL_CIS);
    EXPECT_NEAR(r.excitation_energies[1], REF_H2O_CIS_ccpVDZ_state2, TOL_CIS);
    EXPECT_NEAR(r.excitation_energies[2], REF_H2O_CIS_ccpVDZ_state3, TOL_CIS);
    EXPECT_NEAR(r.excitation_energies[3], REF_H2O_CIS_ccpVDZ_state4, TOL_CIS);
    EXPECT_NEAR(r.excitation_energies[4], REF_H2O_CIS_ccpVDZ_state5, TOL_CIS);
    ASSERT_EQ(r.oscillator_strengths.size(), 5u);
    EXPECT_NEAR(r.oscillator_strengths[0], REF_H2O_CIS_ccpVDZ_f1, TOL_OSC);
    EXPECT_NEAR(r.oscillator_strengths[1], REF_H2O_CIS_ccpVDZ_f2, TOL_OSC);
    EXPECT_NEAR(r.oscillator_strengths[2], REF_H2O_CIS_ccpVDZ_f3, TOL_OSC);
    EXPECT_NEAR(r.oscillator_strengths[3], REF_H2O_CIS_ccpVDZ_f4, TOL_OSC);
    EXPECT_NEAR(r.oscillator_strengths[4], REF_H2O_CIS_ccpVDZ_f5, TOL_OSC);
}

// ============================================================
//  ADC(2) excitation energies (PySCF adc.ADC method='adc(2)')
// ============================================================

// ADC(2) reference values from PySCF EE-ADC(2) using GANSU's geometries
// Generated by: script/gen_adc2_ref.py (conv_tol=1e-12)
// H2: H-H = 0.7122 A;  H2O: O(0,0,0.127) H(0,±0.758,-0.509)
constexpr real_t REF_H2_ADC2_STO3G_state1 = 0.9941726103;
constexpr real_t REF_H2O_ADC2_STO3G_state1 = 0.4469541540;
constexpr real_t REF_H2O_ADC2_STO3G_state2 = 0.5132634097;
constexpr real_t REF_H2O_ADC2_STO3G_state3 = 0.5981435455;

// HF/cc-pVDZ: F(0,0,0.096) H(0,0,-0.860), cart=True
constexpr real_t REF_HF_ADC2_ccpVDZ_state1 = 0.3672433834;
constexpr real_t REF_HF_ADC2_ccpVDZ_state2 = 0.3672433834;
constexpr real_t REF_HF_ADC2_ccpVDZ_state3 = 0.5488840627;

constexpr real_t TOL_ADC2 = 1e-5;       // ADC(2) tolerance (omega iteration, exact)
constexpr real_t TOL_ADC2_HIGH = 1e-5;  // ADC(2) tolerance for higher roots

static GansuResult run_gansu_adc2(const std::string& xyz,
                                   const std::string& basis,
                                   int n_states = 3)
{
    cudaDeviceSynchronize();
    cudaGetLastError();

    ParameterManager params;
    params["xyzfilename"] = xyz;
    params["gbsfilename"] = basis;
    params["method"] = "rhf";
    params["post_hf_method"] = "adc2";
    params["n_excited_states"] = std::to_string(n_states);
    params["convergence_energy_threshold"] = "1e-10";
    params["initial_guess"] = "core";
    params["eri_method"] = "stored";

    std::streambuf* orig_buf = std::cout.rdbuf();
    std::ostringstream null_stream;
    std::cout.rdbuf(null_stream.rdbuf());

    auto hf = HFBuilder::buildHF(params);
    hf->solve();

    std::cout.rdbuf(orig_buf);

    GansuResult result;
    result.hf_total_energy = hf->get_total_energy();
    result.post_hf_energy = hf->get_post_hf_energy();
    result.excitation_energies = hf->get_excitation_energies();

    std::cout << std::setprecision(10) << std::fixed
              << "  GANSU HF total = " << result.hf_total_energy;
    for (size_t i = 0; i < result.excitation_energies.size(); i++) {
        std::cout << "  ADC2[" << i << "] = " << result.excitation_energies[i];
    }
    std::cout << std::endl;

    return result;
}

TEST(ValidationADC2, H2_STO3G) {
    // H2 has 1 occ, 1 vir -> singles dim = 1
    auto r = run_gansu_adc2(XYZ + "H2.xyz", BASIS + "sto-3g.gbs", 1);

    EXPECT_NEAR(r.hf_total_energy, REF_H2_RHF_STO3G, TOL_HF);
    ASSERT_EQ(r.excitation_energies.size(), 1u);
    EXPECT_NEAR(r.excitation_energies[0], REF_H2_ADC2_STO3G_state1, TOL_ADC2);
}

TEST(ValidationADC2, H2O_STO3G) {
    // H2O has 5 occ, 2 vir -> singles dim = 10
    auto r = run_gansu_adc2(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", 3);

    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_HF);
    ASSERT_EQ(r.excitation_energies.size(), 3u);
    EXPECT_NEAR(r.excitation_energies[0], REF_H2O_ADC2_STO3G_state1, TOL_ADC2);
    EXPECT_NEAR(r.excitation_energies[1], REF_H2O_ADC2_STO3G_state2, TOL_ADC2);
    EXPECT_NEAR(r.excitation_energies[2], REF_H2O_ADC2_STO3G_state3, TOL_ADC2_HIGH);
}

TEST(ValidationADC2, HF_ccpVDZ) {
    // HF has 5 occ, 19 vir -> singles dim = 95
    auto r = run_gansu_adc2(XYZ + "HF.xyz", BASIS + "cc-pvdz.gbs", 3);

    EXPECT_NEAR(r.hf_total_energy, REF_HFmol_RHF_ccpVDZ, TOL_HF);
    ASSERT_EQ(r.excitation_energies.size(), 3u);
    EXPECT_NEAR(r.excitation_energies[0], REF_HF_ADC2_ccpVDZ_state1, TOL_ADC2_HIGH);
    EXPECT_NEAR(r.excitation_energies[1], REF_HF_ADC2_ccpVDZ_state2, TOL_ADC2_HIGH);
    EXPECT_NEAR(r.excitation_energies[2], REF_HF_ADC2_ccpVDZ_state3, TOL_ADC2_HIGH);
}

// ============================================================
//  ADC(2) solver mode tests
// ============================================================

static GansuResult run_gansu_adc2_with_solver(const std::string& xyz,
                                               const std::string& basis,
                                               const std::string& solver_mode,
                                               int n_states = 3)
{
    cudaDeviceSynchronize();
    cudaGetLastError();

    ParameterManager params;
    params["xyzfilename"] = xyz;
    params["gbsfilename"] = basis;
    params["method"] = "rhf";
    params["post_hf_method"] = "adc2";
    params["n_excited_states"] = std::to_string(n_states);
    params["convergence_energy_threshold"] = "1e-10";
    params["initial_guess"] = "core";
    params["eri_method"] = "stored";
    params["adc2_solver"] = solver_mode;

    std::streambuf* orig_buf = std::cout.rdbuf();
    std::ostringstream null_stream;
    std::cout.rdbuf(null_stream.rdbuf());

    auto hf = HFBuilder::buildHF(params);
    hf->solve();

    std::cout.rdbuf(orig_buf);

    GansuResult result;
    result.hf_total_energy = hf->get_total_energy();
    result.post_hf_energy = hf->get_post_hf_energy();
    result.excitation_energies = hf->get_excitation_energies();

    std::cout << std::setprecision(10) << std::fixed
              << "  [" << solver_mode << "] GANSU HF total = " << result.hf_total_energy;
    for (size_t i = 0; i < result.excitation_energies.size(); i++) {
        std::cout << "  ADC2[" << i << "] = " << result.excitation_energies[i];
    }
    std::cout << std::endl;

    return result;
}

// schur_static: approximate, looser tolerance
constexpr real_t TOL_ADC2_STATIC = 0.03;  // ~0.005-0.02 Ha error

TEST(ValidationADC2Solver, SchurStatic_H2O_STO3G) {
    auto r = run_gansu_adc2_with_solver(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs",
                                         "schur_static", 3);
    ASSERT_EQ(r.excitation_energies.size(), 3u);
    EXPECT_NEAR(r.excitation_energies[0], REF_H2O_ADC2_STO3G_state1, TOL_ADC2_STATIC);
    EXPECT_NEAR(r.excitation_energies[1], REF_H2O_ADC2_STO3G_state2, TOL_ADC2_STATIC);
    EXPECT_NEAR(r.excitation_energies[2], REF_H2O_ADC2_STO3G_state3, TOL_ADC2_STATIC);
}

// full Davidson: exact, same tight tolerance as schur_omega
TEST(ValidationADC2Solver, Full_H2_STO3G) {
    auto r = run_gansu_adc2_with_solver(XYZ + "H2.xyz", BASIS + "sto-3g.gbs",
                                         "full", 1);
    ASSERT_EQ(r.excitation_energies.size(), 1u);
    EXPECT_NEAR(r.excitation_energies[0], REF_H2_ADC2_STO3G_state1, TOL_ADC2);
}

TEST(ValidationADC2Solver, Full_H2O_STO3G) {
    auto r = run_gansu_adc2_with_solver(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs",
                                         "full", 3);
    ASSERT_EQ(r.excitation_energies.size(), 3u);
    EXPECT_NEAR(r.excitation_energies[0], REF_H2O_ADC2_STO3G_state1, TOL_ADC2);
    EXPECT_NEAR(r.excitation_energies[1], REF_H2O_ADC2_STO3G_state2, TOL_ADC2);
    EXPECT_NEAR(r.excitation_energies[2], REF_H2O_ADC2_STO3G_state3, TOL_ADC2_HIGH);
}

TEST(ValidationADC2Solver, Full_HF_ccpVDZ) {
    auto r = run_gansu_adc2_with_solver(XYZ + "HF.xyz", BASIS + "cc-pvdz.gbs",
                                         "full", 3);
    ASSERT_EQ(r.excitation_energies.size(), 3u);
    EXPECT_NEAR(r.excitation_energies[0], REF_HF_ADC2_ccpVDZ_state1, TOL_ADC2_HIGH);
    EXPECT_NEAR(r.excitation_energies[1], REF_HF_ADC2_ccpVDZ_state2, TOL_ADC2_HIGH);
    EXPECT_NEAR(r.excitation_energies[2], REF_HF_ADC2_ccpVDZ_state3, TOL_ADC2_HIGH);
}

// ============================================================
//  EOM-MP2 excitation energies
// ============================================================

// EOM-MP2 reference values: TODO - generate with PySCF
// For now, use placeholder values (will be updated after first successful run)
// PySCF: from pyscf.ci import cisd; myci = cisd.CISD(mf).run(); myci.nroots=5
// Actually PySCF doesn't have EOM-MP2 directly.
// Reference: run GANSU first, verify against manual calculation, then fix values.

static GansuResult run_gansu_eom_mp2(const std::string& xyz,
                                      const std::string& basis,
                                      int n_states = 3)
{
    cudaDeviceSynchronize();
    cudaGetLastError();

    ParameterManager params;
    params["xyzfilename"] = xyz;
    params["gbsfilename"] = basis;
    params["method"] = "rhf";
    params["post_hf_method"] = "eom_mp2";
    params["n_excited_states"] = std::to_string(n_states);
    params["convergence_energy_threshold"] = "1e-10";
    params["initial_guess"] = "core";
    params["eri_method"] = "stored";

    std::streambuf* orig_buf = std::cout.rdbuf();
    std::ostringstream null_stream;
    std::cout.rdbuf(null_stream.rdbuf());

    auto hf = HFBuilder::buildHF(params);
    hf->solve();

    std::cout.rdbuf(orig_buf);

    GansuResult result;
    result.hf_total_energy = hf->get_total_energy();
    result.post_hf_energy = hf->get_post_hf_energy();
    result.excitation_energies = hf->get_excitation_energies();

    std::cout << std::setprecision(10) << std::fixed
              << "  GANSU HF total = " << result.hf_total_energy;
    for (size_t i = 0; i < result.excitation_energies.size(); i++) {
        std::cout << "  EOM-MP2[" << i << "] = " << result.excitation_energies[i];
    }
    std::cout << std::endl;

    return result;
}

TEST(ValidationEOMMP2, H2_STO3G) {
    auto r = run_gansu_eom_mp2(XYZ + "H2.xyz", BASIS + "sto-3g.gbs", 1);
    EXPECT_NEAR(r.hf_total_energy, REF_H2_RHF_STO3G, TOL_HF);
    ASSERT_EQ(r.excitation_energies.size(), 1u);
    // Print result for reference value generation
    std::cout << "  EOM-MP2 H2/STO-3G state1 = "
              << std::setprecision(10) << r.excitation_energies[0] << std::endl;
}

TEST(ValidationEOMMP2, H2O_STO3G) {
    auto r = run_gansu_eom_mp2(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", 3);
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_HF);
    ASSERT_EQ(r.excitation_energies.size(), 3u);
    // Print results for reference value generation
    for (size_t i = 0; i < r.excitation_energies.size(); i++) {
        std::cout << "  EOM-MP2 H2O/STO-3G state" << i+1 << " = "
                  << std::setprecision(10) << r.excitation_energies[i] << std::endl;
    }
}

// ============================================================
//  CC2 ground-state correlation energy
// ============================================================

// Psi4 reference: H2O/cc-pVDZ (Cartesian, puream=False)
// RHF = -76.0234907752, CC2 corr = -0.2113116818
constexpr real_t REF_H2O_CC2_ccpVDZ_corr = -0.2113116818;

// CC2/STO-3G: For H2O, CC2 corr should be between MP2 (-0.0389637139) and CCSD (-0.0543962594)
// For H2, CC2 == CCSD (only 2 electrons, 1 occ + 1 vir)
constexpr real_t TOL_CC2 = 5e-5;          // CC2 correlation energy tolerance

// run_gansu_eom_cc2 helper is shared with EOM-CC2 tests below

// ============================================================
//  EOM-CC2 excitation energies
// ============================================================

// EOM-CC2 reference values: CC2 ground state verified against Psi4 (CC2 corr = -0.2113116818)
// EOM excitation energies are GANSU regression values (post CC2-T1 fix)
// TODO: update with Psi4 EOM-CC2 or CC-LR reference when available

static GansuResult run_gansu_eom_cc2(const std::string& xyz,
                                      const std::string& basis,
                                      int n_states = 3)
{
    cudaDeviceSynchronize();
    cudaGetLastError();

    ParameterManager params;
    params["xyzfilename"] = xyz;
    params["gbsfilename"] = basis;
    params["method"] = "rhf";
    params["post_hf_method"] = "eom_cc2";
    params["n_excited_states"] = std::to_string(n_states);
    params["convergence_energy_threshold"] = "1e-10";
    params["initial_guess"] = "core";
    params["eri_method"] = "stored";

    std::streambuf* orig_buf = std::cout.rdbuf();
    std::ostringstream null_stream;
    std::cout.rdbuf(null_stream.rdbuf());

    auto hf = HFBuilder::buildHF(params);
    hf->solve();

    std::cout.rdbuf(orig_buf);

    GansuResult result;
    result.hf_total_energy = hf->get_total_energy();
    result.post_hf_energy = hf->get_post_hf_energy();
    result.excitation_energies = hf->get_excitation_energies();

    std::cout << std::setprecision(10) << std::fixed
              << "  GANSU HF total = " << result.hf_total_energy
              << "  CC2 corr = " << result.post_hf_energy;
    for (size_t i = 0; i < result.excitation_energies.size(); i++) {
        std::cout << "  EOM-CC2[" << i << "] = " << result.excitation_energies[i];
    }
    std::cout << std::endl;

    return result;
}

// ---- CC2 ground-state correlation energy tests ----

TEST(ValidationCC2, H2_STO3G) {
    // H2/STO-3G: 1 occ, 1 vir => CC2 == CCSD (exact for 2-electron system)
    auto r = run_gansu_eom_cc2(XYZ + "H2.xyz", BASIS + "sto-3g.gbs", 1);
    EXPECT_NEAR(r.hf_total_energy, REF_H2_RHF_STO3G, TOL_HF);
    // CC2 corr should equal CCSD corr for H2 (both are exact in minimal basis)
    std::cout << "  CC2 H2/STO-3G corr = "
              << std::setprecision(10) << r.post_hf_energy << std::endl;
    EXPECT_LT(r.post_hf_energy, 0.0);  // correlation energy is negative
}

TEST(ValidationCC2, H2O_STO3G) {
    auto r = run_gansu_eom_cc2(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", 1);
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_HF);
    std::cout << "  CC2 H2O/STO-3G corr = "
              << std::setprecision(10) << r.post_hf_energy << std::endl;
    // CC2 corr should be between MP2 and CCSD
    EXPECT_LT(r.post_hf_energy, REF_H2O_MP2_STO3G_corr);    // more negative than MP2
    EXPECT_GT(r.post_hf_energy, REF_H2O_CCSD_STO3G_corr);    // less negative than CCSD
}

TEST(ValidationCC2, H2O_ccpVDZ) {
    // Psi4 reference: CC2 corr = -0.2113116818 Ha (puream=False, Cartesian)
    auto r = run_gansu_eom_cc2(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", 1);
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_CC2_ccpVDZ_corr, TOL_CC2);
    std::cout << "  CC2 H2O/cc-pVDZ corr = "
              << std::setprecision(10) << r.post_hf_energy
              << "  (Psi4: " << REF_H2O_CC2_ccpVDZ_corr << ")" << std::endl;
}

// ---- EOM-CC2 excitation energy tests ----

TEST(ValidationEOMCC2, H2_STO3G) {
    auto r = run_gansu_eom_cc2(XYZ + "H2.xyz", BASIS + "sto-3g.gbs", 1);
    EXPECT_NEAR(r.hf_total_energy, REF_H2_RHF_STO3G, TOL_HF);
    ASSERT_EQ(r.excitation_energies.size(), 1u);
    std::cout << "  EOM-CC2 H2/STO-3G state1 = "
              << std::setprecision(10) << r.excitation_energies[0] << std::endl;
}

TEST(ValidationEOMCC2, H2O_STO3G) {
    auto r = run_gansu_eom_cc2(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", 3);
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_HF);
    ASSERT_EQ(r.excitation_energies.size(), 3u);
    for (size_t i = 0; i < r.excitation_energies.size(); i++) {
        std::cout << "  EOM-CC2 H2O/STO-3G state" << i+1 << " = "
                  << std::setprecision(10) << r.excitation_energies[i] << std::endl;
    }
}

TEST(ValidationEOMCC2, H2O_ccpVDZ) {
    auto r = run_gansu_eom_cc2(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", 5);
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_CC2_ccpVDZ_corr, TOL_CC2);
    ASSERT_EQ(r.excitation_energies.size(), 5u);
    // Sanity checks: excitation energies should be positive, ordered, and in reasonable range
    for (size_t i = 0; i < 5; i++) {
        EXPECT_GT(r.excitation_energies[i], 0.2);   // > ~5.4 eV
        EXPECT_LT(r.excitation_energies[i], 0.7);   // < ~19 eV
        if (i > 0) {
            EXPECT_GE(r.excitation_energies[i], r.excitation_energies[i-1]);
        }
        std::cout << "  EOM-CC2 H2O/cc-pVDZ state" << i+1 << " = "
                  << std::setprecision(10) << r.excitation_energies[i] << std::endl;
    }
}

TEST(ValidationEOMCC2, H2O_ccpVDZ_EnergyOrdering) {
    // Verify EOM-CC2 excitation energies are higher than EOM-CCSD
    // (expected: CC2 is less accurate than CCSD, giving ~0.3 eV higher)
    // EOM-CCSD/PySCF (cart=True): 0.2879, 0.3631, 0.3962, 0.4724, 0.5166
    auto r = run_gansu_eom_cc2(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", 1);
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_HF);
    ASSERT_GE(r.excitation_energies.size(), 1u);
    // EOM-CC2 state 1 should be positive and in a reasonable range
    EXPECT_GT(r.excitation_energies[0], 0.25);  // > ~6.8 eV
    EXPECT_LT(r.excitation_energies[0], 0.35);  // < ~9.5 eV
}

// ============================================================
//  EOM-CCSD excitation energies
// ============================================================

// PySCF reference: cc.eom_rccsd.EOMEESinglet (cart=True for cc-pVDZ)

static GansuResult run_gansu_eom_ccsd(const std::string& xyz,
                                       const std::string& basis,
                                       int n_states = 3)
{
    cudaDeviceSynchronize();
    cudaGetLastError();

    ParameterManager params;
    params["xyzfilename"] = xyz;
    params["gbsfilename"] = basis;
    params["method"] = "rhf";
    params["post_hf_method"] = "eom_ccsd";
    params["n_excited_states"] = std::to_string(n_states);
    params["convergence_energy_threshold"] = "1e-10";
    params["initial_guess"] = "core";
    params["eri_method"] = "stored";

    std::streambuf* orig_buf = std::cout.rdbuf();
    std::ostringstream null_stream;
    std::cout.rdbuf(null_stream.rdbuf());

    auto hf = HFBuilder::buildHF(params);
    hf->solve();

    std::cout.rdbuf(orig_buf);

    GansuResult result;
    result.hf_total_energy = hf->get_total_energy();
    result.post_hf_energy = hf->get_post_hf_energy();
    result.excitation_energies = hf->get_excitation_energies();
    result.oscillator_strengths = hf->get_oscillator_strengths();

    std::cout << std::setprecision(10) << std::fixed
              << "  GANSU HF total = " << result.hf_total_energy
              << "  CCSD corr = " << result.post_hf_energy;
    for (size_t i = 0; i < result.excitation_energies.size(); i++) {
        std::cout << "  EOM-CCSD[" << i << "] = " << result.excitation_energies[i];
    }
    std::cout << std::endl;

    return result;
}

TEST(ValidationEOMCCSD, H2_STO3G) {
    auto r = run_gansu_eom_ccsd(XYZ + "H2.xyz", BASIS + "sto-3g.gbs", 1);
    EXPECT_NEAR(r.hf_total_energy, REF_H2_RHF_STO3G, TOL_HF);
    ASSERT_EQ(r.excitation_energies.size(), 1u);
    EXPECT_GT(r.excitation_energies[0], 0.0);
    std::cout << "  EOM-CCSD H2/STO-3G state1 = "
              << std::setprecision(10) << r.excitation_energies[0] << std::endl;
}

TEST(ValidationEOMCCSD, H2O_STO3G) {
    auto r = run_gansu_eom_ccsd(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", 5);
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_CCSD_STO3G_corr, TOL_POSTHF);
    ASSERT_EQ(r.excitation_energies.size(), 5u);
    EXPECT_NEAR(r.excitation_energies[0], REF_H2O_EOMCCSD_STO3G_state1, TOL_EOMCCSD);
    EXPECT_NEAR(r.excitation_energies[1], REF_H2O_EOMCCSD_STO3G_state2, TOL_EOMCCSD);
    EXPECT_NEAR(r.excitation_energies[2], REF_H2O_EOMCCSD_STO3G_state3, TOL_EOMCCSD);
    EXPECT_NEAR(r.excitation_energies[3], REF_H2O_EOMCCSD_STO3G_state4, TOL_EOMCCSD);
    EXPECT_NEAR(r.excitation_energies[4], REF_H2O_EOMCCSD_STO3G_state5, TOL_EOMCCSD);
}

TEST(ValidationEOMCCSD, H2O_ccpVDZ) {
    auto r = run_gansu_eom_ccsd(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", 5);
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_CCSD_ccpVDZ_corr, TOL_POSTHF_DZ);
    ASSERT_EQ(r.excitation_energies.size(), 5u);
    constexpr real_t TOL_EOMCCSD_ccpVDZ = TOL_EOMCCSD;
    EXPECT_NEAR(r.excitation_energies[0], REF_H2O_EOMCCSD_ccpVDZ_state1, TOL_EOMCCSD_ccpVDZ);
    EXPECT_NEAR(r.excitation_energies[1], REF_H2O_EOMCCSD_ccpVDZ_state2, TOL_EOMCCSD_ccpVDZ);
    EXPECT_NEAR(r.excitation_energies[2], REF_H2O_EOMCCSD_ccpVDZ_state3, TOL_EOMCCSD_ccpVDZ);
    EXPECT_NEAR(r.excitation_energies[3], REF_H2O_EOMCCSD_ccpVDZ_state4, TOL_EOMCCSD_ccpVDZ);
    EXPECT_NEAR(r.excitation_energies[4], REF_H2O_EOMCCSD_ccpVDZ_state5, TOL_EOMCCSD_ccpVDZ);
}


// ============================================================
//  Energy Gradient
// ============================================================
// PySCF reference (cart=True, conv_tol=1e-12, GANSU internal Bohr coordinates):
// H2O/STO-3G:
//   O   1.243e-15   5.265e-16   1.694e-04
//   H   4.393e-16   7.876e-06  -8.468e-05
//   H  -1.682e-15  -7.876e-06  -8.468e-05
// H2O/cc-pVDZ:
//   O   1.781e-17   1.252e-16   6.088e-02
//   H  -1.322e-16   2.829e-02  -3.044e-02
//   H   1.144e-16  -2.829e-02  -3.044e-02

// PySCF reference gradients (Cartesian basis, conv_tol=1e-12)
constexpr real_t REF_H2O_GRAD_STO3G_O_z  =  1.6935712698e-04;
constexpr real_t REF_H2O_GRAD_STO3G_H_y  =  7.8757152984e-06;
constexpr real_t REF_H2O_GRAD_STO3G_H_z  = -8.4678563475e-05;

constexpr real_t REF_H2O_GRAD_ccpVDZ_O_z =  6.0881404097e-02;
constexpr real_t REF_H2O_GRAD_ccpVDZ_H_y =  2.8292229833e-02;
constexpr real_t REF_H2O_GRAD_ccpVDZ_H_z = -3.0440702048e-02;

constexpr real_t TOL_GRAD = 1e-5;  // Gradient tolerance

static std::vector<double> run_gansu_gradient(const std::string& xyz,
                                               const std::string& basis,
                                               const std::string& method = "rhf",
                                               int beta_to_alpha = 0) {
    cudaDeviceSynchronize();
    cudaGetLastError();

    ParameterManager params;
    params["xyzfilename"] = xyz;
    params["gbsfilename"] = basis;
    params["method"] = method;
    params["convergence_energy_threshold"] = "1e-10";
    params["run_type"] = "gradient";
    if (beta_to_alpha != 0) {
        params["beta_to_alpha"] = std::to_string(beta_to_alpha);
    }

    std::streambuf* orig_buf = std::cout.rdbuf();
    std::ostringstream null_stream;
    std::cout.rdbuf(null_stream.rdbuf());

    auto hf = HFBuilder::buildHF(params);
    hf->solve();
    auto grad = hf->compute_Energy_Gradient();

    std::cout.rdbuf(orig_buf);

    std::cout << std::setprecision(10) << std::fixed
              << "  Gradient: ";
    for (size_t i = 0; i < grad.size(); i += 3) {
        std::cout << "[" << grad[i] << ", " << grad[i+1] << ", " << grad[i+2] << "] ";
    }
    std::cout << std::endl;

    return grad;
}

TEST(ValidationGradient, H2O_STO3G) {
    auto g = run_gansu_gradient(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs");
    ASSERT_EQ(g.size(), 9u);  // 3 atoms × 3 directions
    // O: x,y ≈ 0
    EXPECT_NEAR(g[0], 0.0, TOL_GRAD);
    EXPECT_NEAR(g[1], 0.0, TOL_GRAD);
    EXPECT_NEAR(g[2], REF_H2O_GRAD_STO3G_O_z, TOL_GRAD);
    // H1: y,z
    EXPECT_NEAR(g[4], REF_H2O_GRAD_STO3G_H_y, TOL_GRAD);
    EXPECT_NEAR(g[5], REF_H2O_GRAD_STO3G_H_z, TOL_GRAD);
    // H2: -y, same z
    EXPECT_NEAR(g[7], -REF_H2O_GRAD_STO3G_H_y, TOL_GRAD);
    EXPECT_NEAR(g[8], REF_H2O_GRAD_STO3G_H_z, TOL_GRAD);
}

TEST(ValidationGradient, H2O_ccpVDZ) {
    auto g = run_gansu_gradient(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs");
    ASSERT_EQ(g.size(), 9u);
    // O: x,y ≈ 0
    EXPECT_NEAR(g[0], 0.0, TOL_GRAD);
    EXPECT_NEAR(g[1], 0.0, TOL_GRAD);
    EXPECT_NEAR(g[2], REF_H2O_GRAD_ccpVDZ_O_z, TOL_GRAD);
    // H1: y,z
    EXPECT_NEAR(g[4], REF_H2O_GRAD_ccpVDZ_H_y, TOL_GRAD);
    EXPECT_NEAR(g[5], REF_H2O_GRAD_ccpVDZ_H_z, TOL_GRAD);
    // H2: -y, same z
    EXPECT_NEAR(g[7], -REF_H2O_GRAD_ccpVDZ_H_y, TOL_GRAD);
    EXPECT_NEAR(g[8], REF_H2O_GRAD_ccpVDZ_H_z, TOL_GRAD);
}

// UHF gradient: H2O closed-shell UHF should match RHF gradient (cc-pVDZ tests Rys kernel)
TEST(ValidationGradient, H2O_UHF_ccpVDZ) {
    auto g_uhf = run_gansu_gradient(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "uhf");
    auto g_rhf = run_gansu_gradient(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf");
    ASSERT_EQ(g_uhf.size(), 9u);
    ASSERT_EQ(g_rhf.size(), 9u);
    for (size_t i = 0; i < 9; i++) {
        EXPECT_NEAR(g_uhf[i], g_rhf[i], TOL_GRAD);
    }
}

// ============================================================
//  Hash ERI: energy must match Stored ERI (all 3 Fock methods)
// ============================================================

// --- Compact (default) ---

TEST(ValidationHashERI, H2_STO3G_Compact) {
    auto r = run_gansu(XYZ + "H2.xyz", BASIS + "sto-3g.gbs", "rhf", "none", 0, 0, "core", "hash", "", 0, "compact");
    EXPECT_NEAR(r.hf_total_energy, REF_H2_RHF_STO3G, TOL_HF);
}

TEST(ValidationHashERI, H2O_STO3G_Compact) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf", "none", 0, 0, "core", "hash", "", 0, "compact");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_HF);
}

TEST(ValidationHashERI, NH3_STO3G_Compact) {
    auto r = run_gansu(XYZ + "NH3.xyz", BASIS + "sto-3g.gbs", "rhf", "none", 0, 0, "core", "hash", "", 0, "compact");
    EXPECT_NEAR(r.hf_total_energy, REF_NH3_RHF_STO3G, TOL_HF);
}

TEST(ValidationHashERI, CH4_STO3G_Compact) {
    auto r = run_gansu(XYZ + "CH4.xyz", BASIS + "sto-3g.gbs", "rhf", "none", 0, 0, "core", "hash", "", 0, "compact");
    EXPECT_NEAR(r.hf_total_energy, REF_CH4_RHF_STO3G, TOL_HF);
}

TEST(ValidationHashERI, H2O_ccpVDZ_Compact) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf", "none", 0, 0, "core", "hash", "", 0, "compact");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_HF);
}

// --- Indexed ---

TEST(ValidationHashERI, H2O_STO3G_Indexed) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf", "none", 0, 0, "core", "hash", "", 0, "indexed");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_HF);
}

TEST(ValidationHashERI, H2O_ccpVDZ_Indexed) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf", "none", 0, 0, "core", "hash", "", 0, "indexed");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_HF);
}

// --- Fullscan ---

TEST(ValidationHashERI, H2O_STO3G_Fullscan) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf", "none", 0, 0, "core", "hash", "", 0, "fullscan");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_HF);
}

TEST(ValidationHashERI, H2O_ccpVDZ_Fullscan) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf", "none", 0, 0, "core", "hash", "", 0, "fullscan");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_HF);
}

// ============================================================
//  RI post-HF excited states (placed after reference value definitions)
// ============================================================

TEST(ValidationRI_PostHF, H2O_ADC2_STO3G) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "adc2", 0, 0, "core", "ri",
                       AUX_BASIS + "cc-pvdz-rifit.gbs");
    ASSERT_GE(r.excitation_energies.size(), 3u);
    EXPECT_NEAR(r.excitation_energies[0], REF_H2O_ADC2_STO3G_state1, TOL_RI);
    EXPECT_NEAR(r.excitation_energies[1], REF_H2O_ADC2_STO3G_state2, TOL_RI);
    EXPECT_NEAR(r.excitation_energies[2], REF_H2O_ADC2_STO3G_state3, TOL_RI);
}

TEST(ValidationRI_PostHF, H2O_EOM_CCSD_STO3G) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "eom_ccsd", 0, 0, "core", "ri",
                       AUX_BASIS + "cc-pvdz-rifit.gbs");
    ASSERT_GE(r.excitation_energies.size(), 5u);
    // RI fitting error propagates through CCSD + EOM: ~3 mHa for STO-3G
    constexpr real_t TOL_RI_EOM = 5e-3;
    EXPECT_NEAR(r.excitation_energies[0], REF_H2O_EOMCCSD_STO3G_state1, TOL_RI_EOM);
    EXPECT_NEAR(r.excitation_energies[1], REF_H2O_EOMCCSD_STO3G_state2, TOL_RI_EOM);
    EXPECT_NEAR(r.excitation_energies[2], REF_H2O_EOMCCSD_STO3G_state3, TOL_RI_EOM);
    EXPECT_NEAR(r.excitation_energies[3], REF_H2O_EOMCCSD_STO3G_state4, TOL_RI_EOM);
    EXPECT_NEAR(r.excitation_energies[4], REF_H2O_EOMCCSD_STO3G_state5, TOL_RI_EOM);
}

// ============================================================
//  Direct SCF post-HF validation
//  Direct SCF reconstructs AO ERI lazily for post-HF;
//  results must match Stored ERI within TOL_POSTHF.
// ============================================================

TEST(ValidationDirect_PostHF, H2O_MP2_STO3G) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "mp2", 0, 0, "core", "direct");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_MP2_STO3G_corr, TOL_POSTHF);
}

TEST(ValidationDirect_PostHF, H2O_CCSD_STO3G) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "ccsd", 0, 0, "core", "direct");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_CCSD_STO3G_corr, TOL_POSTHF);
}

TEST(ValidationDirect_PostHF, H2O_CCSD_T_STO3G) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "ccsd_t", 0, 0, "core", "direct");
    real_t total = r.hf_total_energy + r.post_hf_energy;
    EXPECT_NEAR(total, REF_H2O_CCSDT_STO3G_total, TOL_POSTHF);
}

TEST(ValidationDirect_PostHF, H2O_FCI_STO3G) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "fci", 0, 0, "core", "direct");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_STO3G, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_FCI_STO3G_corr, TOL_POSTHF);
}

TEST(ValidationDirect_PostHF, H2O_CIS_STO3G) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "cis", 0, 0, "core", "direct");
    ASSERT_GE(r.excitation_energies.size(), 5u);
    EXPECT_NEAR(r.excitation_energies[0], REF_H2O_CIS_STO3G_state1, TOL_CIS);
    EXPECT_NEAR(r.excitation_energies[1], REF_H2O_CIS_STO3G_state2, TOL_CIS);
    EXPECT_NEAR(r.excitation_energies[2], REF_H2O_CIS_STO3G_state3, TOL_CIS);
}

TEST(ValidationDirect_PostHF, H2O_EOM_CCSD_STO3G) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "sto-3g.gbs", "rhf",
                       "eom_ccsd", 0, 0, "core", "direct");
    ASSERT_GE(r.excitation_energies.size(), 5u);
    // Uses TOL_EOMCCSD (3e-3): known GANSU vs PySCF discrepancy for EOM-CCSD
    EXPECT_NEAR(r.excitation_energies[0], REF_H2O_EOMCCSD_STO3G_state1, TOL_EOMCCSD);
    EXPECT_NEAR(r.excitation_energies[1], REF_H2O_EOMCCSD_STO3G_state2, TOL_EOMCCSD);
    EXPECT_NEAR(r.excitation_energies[2], REF_H2O_EOMCCSD_STO3G_state3, TOL_EOMCCSD);
}

TEST(ValidationDirect_PostHF, H2O_MP2_ccpVDZ) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "mp2", 0, 0, "core", "direct");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_MP2_ccpVDZ_corr, TOL_POSTHF_DZ);
}

TEST(ValidationDirect_PostHF, H2O_CCSD_ccpVDZ) {
    auto r = run_gansu(XYZ + "H2O.xyz", BASIS + "cc-pvdz.gbs", "rhf",
                       "ccsd", 0, 0, "core", "direct");
    EXPECT_NEAR(r.hf_total_energy, REF_H2O_RHF_ccpVDZ, TOL_HF);
    EXPECT_NEAR(r.post_hf_energy, REF_H2O_CCSD_ccpVDZ_corr, TOL_POSTHF_DZ);
}

