/*
 * GANSU: GPU Accelerated Numerical Simulation Utility
 *
 * Copyright (c) 2025-2026, Hiroshima University and Fujitsu Limited
 * All rights reserved.
 *
 * This software is licensed under the BSD 3-Clause License.
 */

/**
 * @file spherical_transform.hpp
 * @brief Cartesian → Spherical (real solid harmonics) basis transformation.
 *
 * GANSU's integral engines (Rys quadrature, McMurchie-Davidson) operate on
 * Cartesian Gaussian basis functions natively.  This module provides the
 * external transformation that converts Cartesian-basis matrices (S, T, V,
 * H_core, F, ERI) to spherical-basis matrices, so that GANSU can match
 * standard cc-pVDZ / cc-pVTZ etc. results from ORCA, PySCF, NWChem etc.
 *
 * Ordering follows the Molden file format spec
 * (https://www.theochem.ru.nl/molden/molden_format.html):
 *
 *   Cartesian (matches GANSU's `AngularMomentums` table in types.hpp):
 *     6D : xx, yy, zz, xy, xz, yz
 *     10F: xxx, yyy, zzz, xyy, xxy, xxz, xzz, yzz, yyz, xyz
 *     15G: xxxx, yyyy, zzzz, xxxy, xxxz, xyyy, yyyz, xzzz, yzzz,
 *          xxyy, xxzz, yyzz, xxyz, xyyz, xyzz
 *
 *   Spherical (Molden order, m-quantum number order):
 *     5D : d_0, d_+1, d_-1, d_+2, d_-2
 *     7F : f_0, f_+1, f_-1, f_+2, f_-2, f_+3, f_-3
 *     9G : g_0, g_+1, g_-1, g_+2, g_-2, g_+3, g_-3, g_+4, g_-4
 *
 * The 5×6 / 7×10 / 9×15 transformation matrices below assume both bases
 * are unit-normalized in physical (Hilbert) space.  GANSU's basis_set.hpp
 * normalizes per-shell rather than per-(lx,ly,lz); we apply additional
 * (2l-1)!! correction factors below so the net transformation produces
 * physical spherical functions identical to those generated by codes that
 * use the standard per-(lx,ly,lz) Cartesian normalization (PySCF, ORCA).
 *
 * Reference:
 *   Schlegel, H. B.; Frisch, M. J.  Int. J. Quantum Chem. 54, 83 (1995):
 *     "Transformation between Cartesian and pure spherical harmonic Gaussians"
 *
 * Validation target: Benzene cc-pVDZ RHF energy matches ORCA 6 spherical-d
 * default (-230.72232 Ha) to ≤ 1e-9 Ha precision.
 */

#pragma once

#include <cmath>
#include <vector>
#include <stdexcept>
#include "types.hpp"

// Forward declaration of cublasHandle_t so this header need not pull in
// <cublas_v2.h> — it is also included by host-only .cpp translation units
// (spherical_transform.cpp) that are not compiled by nvcc.  A repeated
// identical typedef (when a .cu also includes <cublas_v2.h>) is well-formed.
struct cublasContext;
typedef struct cublasContext* cublasHandle_t;

namespace gansu::spherical {

/**
 * @brief Number of spherical basis functions for shell type L.
 *        = 2L + 1   (vs Cartesian (L+1)(L+2)/2)
 */
inline int shell_type_to_num_sph(int L) {
    return 2 * L + 1;
}

/**
 * @brief Cartesian → Spherical transformation matrix (per shell).
 *
 * Returns U[2L+1, (L+1)(L+2)/2] such that:
 *   φ_sph[m_index] = Σ_k  U[m_index, k]  φ_cart[k]
 * where φ_cart is in GANSU's AngularMomentums[L] order
 * and φ_sph is in Molden's m-order: 0, +1, -1, +2, -2, +3, -3, ...
 *
 * For L ∈ {0, 1}, returns identity (1 sph = 1 cart, no transformation needed).
 * For L ∈ {2, 3, 4}, returns the proper Cart→Sph matrix.
 * For higher L, throws.
 */
inline std::vector<std::vector<real_t>> get_cart_to_sph_matrix(int L) {
    if (L == 0) {
        return {{1.0}};   // s shell: trivial 1×1
    }
    if (L == 1) {
        // p shell: Cartesian {px, py, pz} matches Spherical {p+1, p-1, p0}
        // but Molden p order is also Cartesian (px, py, pz) - no transform needed.
        return {{1.0, 0.0, 0.0},
                {0.0, 1.0, 0.0},
                {0.0, 0.0, 1.0}};
    }
    if (L == 2) {
        // d shell: Cart [xx, yy, zz, xy, xz, yz] → Sph [d0, d+1, d-1, d+2, d-2]
        //
        // For unit-normalized Cartesian Gaussians (each φ_{lmn} unit-normalized
        // in physical space — confirmed empirically: S[d_xx,d_xx] = S[d_xy,d_xy]
        // = 1.0 in GANSU's basis), the transformation to unit-normalized real
        // spherical harmonics is:
        //
        //   d_0     (m= 0): coeff (1/2)·(2zz − xx − yy)  → row [-1/2, -1/2, 1, 0, 0, 0]
        //                   Verification: ||·||² = 1/4 + 1/4 + 4 + 2·(1/2)(1/2)·1/3
        //                                         − 4·(1)(1/2)·1/3 − 4·(1)(1/2)·1/3
        //                                = 4 → ×1/4 absorbed into the 1/2 factor → 1
        //
        //   d_+1    (m=+1): coeff = xz   (cross term — already unit-normalized)
        //   d_-1    (m=-1): coeff = yz
        //
        //   d_+2    (m=+2): coeff (√3/2)·(xx − yy)
        //                   Verification: ||·||² = 3/4 + 3/4 − 2·(√3/2)²·(1/3) = 1
        //
        //   d_-2    (m=-2): coeff = xy
        //
        // NOTE: an earlier draft included spurious √3 factors on the m=±1, ±2
        // cross terms — that was incorrect.  Cross-product polynomials (xy, xz,
        // yz) are already unit-normalized as Cartesian Gaussians, so the Cart→
        // Sph mapping is identity for m=±1 and m=−2.  Only the "axial" parts of
        // m=0 and m=+2 (involving xx, yy, zz) carry the √3/normalization scaling.
        const real_t s3   = std::sqrt(3.0);
        const real_t hs3  = s3 / 2.0;
        return {
            // xx     yy     zz    xy   xz   yz
            { -0.5,  -0.5,  1.0,  0.0, 0.0, 0.0 },   // d_0   = (1/2)·(2zz - xx - yy)
            {  0.0,   0.0,  0.0,  0.0, 1.0, 0.0 },   // d_+1  = xz
            {  0.0,   0.0,  0.0,  0.0, 0.0, 1.0 },   // d_-1  = yz
            {  hs3,  -hs3,  0.0,  0.0, 0.0, 0.0 },   // d_+2  = (√3/2)·(xx - yy)
            {  0.0,   0.0,  0.0,  1.0, 0.0, 0.0 }    // d_-2  = xy
        };
    }
    if (L == 3) {
        // f shell: Cart [xxx, yyy, zzz, xyy, xxy, xxz, xzz, yzz, yyz, xyz]
        //       →  Sph (Molden) [f_0, f_+1, f_-1, f_+2, f_-2, f_+3, f_-3]
        //
        // Derivation: each row r_m,k = c_k · √f_k / ||Z_l^m||, where
        //   - Z_l^m is the unnormalized real solid harmonic polynomial
        //     (Condon-Shortley, see e.g. Helgaker–Jørgensen–Olsen Eq. (6.4.36))
        //   - c_k is the coefficient of x^lx y^ly z^lz in Z_l^m
        //   - f_k = (2lx-1)!!(2ly-1)!!(2lz-1)!! is the Cart unit-norm factor
        //   - ||Z||² is computed under the e^{-2αr²} weight
        // Verified to reproduce the d-shell matrix above when applied to L=2.
        const real_t s2  = std::sqrt(2.0);
        const real_t s3  = std::sqrt(3.0);
        const real_t s5  = std::sqrt(5.0);
        const real_t s6  = std::sqrt(6.0);
        const real_t s10 = std::sqrt(10.0);
        const real_t s30 = std::sqrt(30.0);
        return {
            // xxx        yyy        zzz   xyy           xxy           xxz       xzz       yzz       yyz       xyz
            { 0.0,        0.0,       1.0,  0.0,          0.0,         -3.0/(2.0*s5), 0.0, 0.0, -3.0/(2.0*s5), 0.0 }, // f_0
            { -s6/4.0,    0.0,       0.0, -s30/20.0,     0.0,          0.0,      s30/5.0,  0.0,     0.0,      0.0 }, // f_+1
            { 0.0,       -s6/4.0,    0.0,  0.0,         -s30/20.0,     0.0,      0.0,      s30/5.0, 0.0,      0.0 }, // f_-1
            { 0.0,        0.0,       0.0,  0.0,          0.0,          s3/2.0,   0.0,      0.0,    -s3/2.0,   0.0 }, // f_+2
            { 0.0,        0.0,       0.0,  0.0,          0.0,          0.0,      0.0,      0.0,     0.0,      1.0 }, // f_-2
            { s10/4.0,    0.0,       0.0, -3.0*s2/4.0,   0.0,          0.0,      0.0,      0.0,     0.0,      0.0 }, // f_+3
            { 0.0,       -s10/4.0,   0.0,  0.0,          3.0*s2/4.0,   0.0,      0.0,      0.0,     0.0,      0.0 }  // f_-3
        };
    }
    if (L == 4) {
        // g shell: Cart [xxxx, yyyy, zzzz, xxxy, xxxz, xyyy, yyyz, xzzz, yzzz,
        //                xxyy, xxzz, yyzz, xxyz, xyyz, xyzz]
        //       →  Sph (Molden) [g_0, g_+1, g_-1, g_+2, g_-2, g_+3, g_-3, g_+4, g_-4]
        const real_t s2   = std::sqrt(2.0);
        const real_t s3   = std::sqrt(3.0);
        const real_t s5   = std::sqrt(5.0);
        const real_t s7   = std::sqrt(7.0);
        const real_t s10  = std::sqrt(10.0);
        const real_t s14  = std::sqrt(14.0);
        const real_t s21  = std::sqrt(21.0);
        const real_t s35  = std::sqrt(35.0);
        const real_t s70  = std::sqrt(70.0);
        const real_t s105 = std::sqrt(105.0);
        // g_0  norm constants
        const real_t c_xxyy_0 = 9.0 / (4.0 * s105);        // = 3√105/140
        const real_t c_zz_0   = -9.0 / s105;               // = -3√105/35  (xxzz / yyzz)
        // g_+1 / g_-1 constants
        const real_t c_a_1    = -3.0 * s70 / 28.0;         // -3√70/28
        const real_t c_b_1    = -3.0 * s14 / 28.0;         // -3√14/28
        const real_t c_c_1    =  s70 / 7.0;                //  √70/7
        // g_+2 constants
        const real_t c_zz_2   = 3.0 * s21 / 14.0;          //  3√21/14
        // g_-2 constants
        const real_t c_xy_2   = -s35 / 14.0;               // -√35/14
        const real_t c_xyzz_2 =  3.0 * s7 / 7.0;           //  3√7/7
        // g_+3 / g_-3 constants
        const real_t c_a_3    =  s10 / 4.0;                //  √10/4
        const real_t c_b_3    = -3.0 * s2 / 4.0;           // -3√2/4
        // g_+4 constants
        const real_t c_a_4    =  s35 / 8.0;                //  √35/8
        const real_t c_b_4    = -3.0 * s3 / 4.0;           // -3√3/4
        // g_-4 constants
        const real_t c_a_4n   =  s5 / 2.0;                 //  √5/2
        return {
            // xxxx     yyyy     zzzz   xxxy        xxxz      xyyy        yyyz      xzzz      yzzz     xxyy        xxzz      yyzz      xxyz      xyyz      xyzz
            { 3.0/8.0,  3.0/8.0, 1.0,   0.0,        0.0,      0.0,        0.0,      0.0,      0.0,     c_xxyy_0,   c_zz_0,   c_zz_0,   0.0,      0.0,      0.0      }, // g_0
            { 0.0,      0.0,     0.0,   0.0,        c_a_1,    0.0,        0.0,      c_c_1,    0.0,     0.0,        0.0,      0.0,      0.0,      c_b_1,    0.0      }, // g_+1
            { 0.0,      0.0,     0.0,   0.0,        0.0,      0.0,        c_a_1,    0.0,      c_c_1,   0.0,        0.0,      0.0,      c_b_1,    0.0,      0.0      }, // g_-1
            { -s5/4.0,  s5/4.0,  0.0,   0.0,        0.0,      0.0,        0.0,      0.0,      0.0,     0.0,        c_zz_2,  -c_zz_2,   0.0,      0.0,      0.0      }, // g_+2
            { 0.0,      0.0,     0.0,   c_xy_2,     0.0,      c_xy_2,     0.0,      0.0,      0.0,     0.0,        0.0,      0.0,      0.0,      0.0,      c_xyzz_2 }, // g_-2
            { 0.0,      0.0,     0.0,   0.0,        c_a_3,    0.0,        0.0,      0.0,      0.0,     0.0,        0.0,      0.0,      0.0,      c_b_3,    0.0      }, // g_+3
            { 0.0,      0.0,     0.0,   0.0,        0.0,      0.0,       -c_a_3,    0.0,      0.0,     0.0,        0.0,      0.0,     -c_b_3,    0.0,      0.0      }, // g_-3
            { c_a_4,    c_a_4,   0.0,   0.0,        0.0,      0.0,        0.0,      0.0,      0.0,     c_b_4,      0.0,      0.0,      0.0,      0.0,      0.0      }, // g_+4
            { 0.0,      0.0,     0.0,   c_a_4n,     0.0,     -c_a_4n,     0.0,      0.0,      0.0,     0.0,        0.0,      0.0,      0.0,      0.0,      0.0      }  // g_-4
        };
    }
    throw std::runtime_error("spherical_transform: shell L > 4 not supported");
}

/**
 * @brief Total number of spherical basis functions across all shells.
 *
 * Iterates per-shell types and replaces Cartesian (L+1)(L+2)/2 with
 * Spherical (2L+1) where applicable.  s and p shells unchanged.
 */
inline int total_num_sph_basis(const std::vector<int>& shell_types) {
    int total = 0;
    for (int L : shell_types) {
        total += shell_type_to_num_sph(L);
    }
    return total;
}

/**
 * @brief Apply Cartesian → Spherical transformation to a 2-index matrix.
 *
 * Input  : M_cart[nbf_cart, nbf_cart]  (e.g., S, T, V, H_core, F)
 * Output : M_sph [nbf_sph,  nbf_sph]
 *
 * Algorithm: M_sph = U M_cart U^T, where U is block-diagonal per-shell.
 *
 * @param M_cart    input Cartesian-basis matrix (row-major)
 * @param M_sph     output spherical-basis matrix (row-major, pre-allocated)
 * @param shell_types  per-shell L values (one entry per shell, NOT per BF)
 * @param shell_offsets_cart  start index of each shell in Cartesian basis
 * @param shell_offsets_sph   start index of each shell in spherical basis
 */
void transform_matrix_cart_to_sph(
    const real_t* M_cart,
    real_t* M_sph,
    const std::vector<int>& shell_types,
    const std::vector<int>& shell_offsets_cart,
    const std::vector<int>& shell_offsets_sph);

/**
 * @brief Host "reverse" 2-index transform for a DENSITY-like (contravariant)
 *        matrix:  M_cart = Uᵀ · M_sph · U  ([nbf_sph × nbf_sph] → [nc × nc]).
 *
 * Host (Eigen) counterpart of transform_matrix_sph_to_cart_device. Used by the
 * ECP gradient under spherical basis: the ECP integral derivatives are built in
 * the Cartesian primitive basis, so they must contract a Cartesian density
 * D_cart = Uᵀ D_sph U.
 */
void transform_matrix_sph_to_cart(
    const real_t* M_sph,
    real_t* M_cart,
    const std::vector<int>& shell_types,
    const std::vector<int>& shell_offsets_cart,
    const std::vector<int>& shell_offsets_sph);

/**
 * @brief Apply Cartesian → Spherical transformation to a 4-index ERI tensor.
 *
 * Input  : ERI_cart[nbf⁴_cart]  (row-major (p,q,r,s) chemist notation)
 * Output : ERI_sph [nbf⁴_sph ]
 *
 * Performs four sequential 2-index transformations, one per ERI axis.
 */
void transform_eri_cart_to_sph(
    const real_t* ERI_cart,
    real_t* ERI_sph,
    const std::vector<int>& shell_types,
    const std::vector<int>& shell_offsets_cart,
    const std::vector<int>& shell_offsets_sph);

/**
 * @brief GPU variant of the 4-index ERI Cart→Sph transform.
 *
 * Operates entirely on device memory: d_eri_cart (input) and d_eri_sph
 * (output) are both device pointers.  Internally uses 4 cuBLAS DGEMM
 * calls (Stages 1 & 4 are single GEMMs; Stages 2 & 3 are strided-batched
 * GEMMs) with intermediate buffers allocated/freed on-device as each
 * stage progresses, keeping peak GPU footprint at ~(cart + intermediate)
 * rather than (cart + sph + 3·intermediate).
 *
 * @param d_eri_cart  device pointer to row-major Cart ERI tensor (nbf_cart⁴)
 * @param d_eri_sph   device pointer to pre-allocated row-major Sph ERI
 *                    output tensor (nbf_sph⁴)
 * @param shell_types          per-shell L values
 * @param shell_offsets_cart   start index of each shell in Cart basis
 * @param shell_offsets_sph    start index of each shell in Sph basis
 */
void transform_eri_cart_to_sph_device(
    const real_t* d_eri_cart,
    real_t* d_eri_sph,
    const std::vector<int>& shell_types,
    const std::vector<int>& shell_offsets_cart,
    const std::vector<int>& shell_offsets_sph);

/**
 * @brief Device variant of the 2-index Cart→Sph transform.
 *
 * Input  : d_M_cart[nbf_cart × nbf_cart]  (device, row-major)
 * Output : d_M_sph [nbf_sph  × nbf_sph ]  (device, row-major)
 *
 * Used for the auxiliary V matrix (P|Q) in RI; small enough that the
 * device variant is here purely for consistency / avoiding D2H/H2D
 * round-trips around the RI build.
 */
void transform_matrix_cart_to_sph_device(
    const real_t* d_M_cart,
    real_t* d_M_sph,
    const std::vector<int>& shell_types,
    const std::vector<int>& shell_offsets_cart,
    const std::vector<int>& shell_offsets_sph);

/**
 * @brief Device "reverse" 2-index transform for a DENSITY-like (contravariant)
 *        matrix:  M_cart = Uᵀ · M_sph · U   ([nbf_sph × nbf_sph] → [nc × nc]).
 *
 * The coefficient matrix expressed in Cartesian is C_cart = Uᵀ C_sph, so the
 * density D_cart = C_cart C_cartᵀ = Uᵀ D_sph U.  Used by the back-transform Fock
 * builds (Direct/Hash) that run their 2e kernels in Cartesian: D_sph → D_cart →
 * (Cartesian kernel) → G_cart → G_sph = U G_cart Uᵀ via the forward transform.
 */
void transform_matrix_sph_to_cart_device(
    const real_t* d_M_sph,
    real_t* d_M_cart,
    const std::vector<int>& shell_types,
    const std::vector<int>& shell_offsets_cart,
    const std::vector<int>& shell_offsets_sph);

/**
 * @brief Express the MO coefficients in the Cartesian AO basis:
 *        C_cart[nc × nmo] = Uᵀ · C_sph[ns × nmo]   (AO axis only).
 *
 * Both row-major.  Used by the back-transform energy gradient (stored ERI):
 * with C_cart / D_cart = Uᵀ D_sph U in Cartesian, the existing Cartesian
 * gradient kernels give dE/dR exactly (U is geometry-independent, and for exact
 * ERIs E_sph = E_cart).  @p nmo is the number of MO columns (= ns for RHF).
 */
void transform_coeff_sph_to_cart_device(
    const real_t* d_C_sph,
    real_t* d_C_cart,
    int nmo,
    const std::vector<int>& shell_types,
    const std::vector<int>& shell_offsets_cart,
    const std::vector<int>& shell_offsets_sph);

/**
 * @brief Device 3-index Cart→Sph transform, used for the RI 3-center
 *        (P|μν) tensor where P is in the auxiliary basis and μ, ν are
 *        in the orbital basis.
 *
 * Input  : d_T_cart[nbf_aux_cart × nbf_orb_cart × nbf_orb_cart]
 * Output : d_T_sph [nbf_aux_sph  × nbf_orb_sph  × nbf_orb_sph ]
 *
 * Three sequential single-index transforms, each a cuBLAS DGEMM:
 *   Stage 1 (P axis, aux):  single dgemm (M = ns_aux, K = nc_aux, N = nc_orb²)
 *   Stage 2 (μ axis, orb):  strided-batched dgemm — batch over P, each
 *                           batch is (M = ns_orb, K = nc_orb, N = nc_orb)
 *   Stage 3 (ν axis, orb):  single dgemm with op_B = T applied to U_orb
 *                           (M = ns_aux · ns_orb, K = nc_orb, N = ns_orb)
 *
 * Intermediates are freed as each stage consumes them, keeping peak
 * device footprint at ~(input + largest intermediate).
 *
 * @param d_T_cart                   input device pointer
 * @param d_T_sph                    pre-allocated output device pointer
 * @param aux_shell_types            per-shell L for the auxiliary basis
 * @param aux_shell_offsets_cart     Cart shell offsets for the aux basis
 * @param aux_shell_offsets_sph      Sph  shell offsets for the aux basis
 * @param orb_shell_types            per-shell L for the orbital basis
 * @param orb_shell_offsets_cart     Cart shell offsets for the orbital basis
 * @param orb_shell_offsets_sph      Sph  shell offsets for the orbital basis
 */
void transform_3index_cart_to_sph_device(
    const real_t* d_T_cart,
    real_t* d_T_sph,
    const std::vector<int>& aux_shell_types,
    const std::vector<int>& aux_shell_offsets_cart,
    const std::vector<int>& aux_shell_offsets_sph,
    const std::vector<int>& orb_shell_types,
    const std::vector<int>& orb_shell_offsets_cart,
    const std::vector<int>& orb_shell_offsets_sph);

/**
 * @brief Build the block-diagonal Cart→Sph matrix U[nbf_sph × nbf_cart]
 *        (row-major) on the *current* CUDA device and return the device
 *        pointer via @p d_U_out.  Caller owns the allocation (cudaFree).
 *
 * Phase 2b (distributed RI) folds the auxiliary-axis transform into a
 * precomputed M = L_sph⁻¹ · U_aux, and reuses a per-device U_orb for the
 * chunked orbital-pair transform — both need this raw uploader.
 *
 * @param shell_types        per-shell L values
 * @param shell_offsets_cart Cart shell offsets (size n_shells+1)
 * @param shell_offsets_sph  Sph  shell offsets (size n_shells+1)
 * @param d_U_out            receives a freshly cudaMalloc'd device pointer
 */
void build_cart_to_sph_U_device(
    const std::vector<int>& shell_types,
    const std::vector<int>& shell_offsets_cart,
    const std::vector<int>& shell_offsets_sph,
    real_t** d_U_out);

/**
 * @brief Device 3-index "reverse" Sph→Cart transform — the transpose of
 *        transform_3index_cart_to_sph_device on all three axes:
 *
 *   T_cart[p,m,n] = Σ_{P,μ,ν} U_aux[P,p] · U_orb[μ,m] · U_orb[ν,n] · T_sph[P,μ,ν]
 *
 * Input  : d_T_sph [ns_aux × ns_orb × ns_orb]   (device, row-major)
 * Output : d_T_cart[nc_aux × nc_orb × nc_orb]   (device, row-major, pre-allocated)
 *
 * Used by the spherical RI energy gradient: the RI-gradient "Γ" intermediates
 * (Γ^(3)_{P,μν}) are assembled in the spherical basis (where the J^{-1} metric
 * lives), then back-transformed here so the Cartesian 3c2e-derivative kernels —
 * which differentiate the underlying Cartesian Gaussians — contract the right
 * quantity.  Exact because U is geometry-independent and (P|μν)_sph = U_aux U
 * U (P|μν)_cart, so Σ Γ_sph · d(P|μν)_sph/dR = Σ Γ_cart · d(P|μν)_cart/dR.
 *
 * Three sequential DGEMMs (mirror of the forward, with each U transposed):
 *   Stage 1 (P aux):  single dgemm, U_auxᵀ on the leading axis
 *   Stage 2 (ν orb):  single dgemm, U_orb on the trailing axis
 *   Stage 3 (μ orb):  strided-batched dgemm over the nc_aux leading slabs
 */
void transform_3index_sph_to_cart_device(
    const real_t* d_T_sph,
    real_t* d_T_cart,
    const std::vector<int>& aux_shell_types,
    const std::vector<int>& aux_shell_offsets_cart,
    const std::vector<int>& aux_shell_offsets_sph,
    const std::vector<int>& orb_shell_types,
    const std::vector<int>& orb_shell_offsets_cart,
    const std::vector<int>& orb_shell_offsets_sph);

/**
 * @brief Transform only the two orbital indices (μ, ν) of a 3-index tensor
 *        from Cart to Sph, leaving the leading axis untouched.
 *
 * Input  : d_in [n_lead × nc_orb × nc_orb]   (row-major)
 * Output : d_out[n_lead × ns_orb × ns_orb]   (row-major, pre-allocated)
 *
 * This is exactly Stages 2 & 3 of transform_3index_cart_to_sph_device with
 * the leading auxiliary axis (there ns_aux) replaced by an arbitrary
 * @p n_lead.  Phase 2b uses it per aux-chunk: the leading axis is the chunk
 * of *Cartesian* auxiliary functions (nfunc_c), whose Cart→Sph mixing is
 * already folded into M, so only μ, ν need transforming here.
 *
 * Unlike the self-contained transforms above, this variant takes a caller
 * @p handle (so it runs on a specific GPU's stream in the multi-GPU loop)
 * and caller-provided scratch — it performs NO cudaMalloc/cudaFree and NO
 * device sync, preserving multi-GPU concurrency.
 *
 * @param handle    cuBLAS handle bound to the target device & stream
 * @param d_in      input  [n_lead × nc_orb × nc_orb] (device)
 * @param d_out     output [n_lead × ns_orb × ns_orb] (device, pre-allocated)
 * @param d_T_work  scratch [n_lead × ns_orb × nc_orb] (device, pre-allocated)
 * @param d_U_orb   prebuilt orbital U [ns_orb × nc_orb] (device, via
 *                  build_cart_to_sph_U_device)
 * @param n_lead    number of leading (untouched) functions
 * @param nc_orb    Cart orbital count
 * @param ns_orb    Sph  orbital count
 */
void transform_orbital_pair_cart_to_sph_device(
    cublasHandle_t handle,
    const real_t* d_in,
    real_t* d_out,
    real_t* d_T_work,
    const real_t* d_U_orb,
    int n_lead,
    int nc_orb,
    int ns_orb);

} // namespace gansu::spherical
